const regionsAndCities = new Map([
    [`Kanto`, new Map([
        [`Bourg Palette`, ``],
        [`Lavanville`, ``],
        [`Argenta`, ``],
        [`Azuria`, ``],
        [`Carmin sur Mer`, ``],
        [`Céladopole`, ``],
        [`Parmanie`, ``],
        [`Safrania`, ``],
        [`Cramois'île`, ``],
        [`Jadielle`, ``],
    ])],
    [`Îles Sevii`, new Map([
        [`Île 1`, ``],
        [`Île 2`, ``],
        [`Île 3`, ``],
        [`Île 4`, ``],
        [`Île 5`, ``],
        [`Île 6`, ``],
        [`Île 7`, ``],
    ])],
    [`Johto`, new Map([
        [`Bourg Geon`, ``],
        [`Ville Griotte`, ``],
        [`Mauville`, ``],
        [`Ecorcia`, ``],
        [`Doublonville`, ``],
        [`Rosalia`, ``],
        [`Irisia`, ``],
        [`Oliville`, ``],
        [`Acajou`, ``],
        [`Ebènelle`, ``],
    ])],
    [`Hoenn`, new Map([
        [`Bourg-en-Vol`, ``],
        [`Rosyères`, ``],
        [`Poivressel`, ``],
        [`Vergazon`, ``],
        [`Autéquia`, ``],
        [`Nénucrique`, ``],
        [`Pacifiville`, ``],
        [`Ville Griotte`, ``],
        [`Mérouville`, ``],
        [`Myokara`, ``],
        [`Lavandia`, ``],
        [`Vermilava`, ``],
        [`Clémenti-Ville`, ``],
        [`Cimetronelle`, ``],
        [`Algatia`, ``],
        [`Atalanopolis`, ``],
    ])],
    [`Sinnoh`, new Map([
        [`Bonaugure`, ``],
        [`Littorella`, ``],
        [`Féli-Cité`, ``],
        [`Floraville`, ``],
        [`Bonville`, ``],
        [`Célestia`, ``],
        [`Charbourg`, ``],
        [`Vestigion`, ``],
        [`Voilaroc`, ``],
        [`Verchamps`, ``],
        [`Unionpolis`, ``],
        [`Joliberges`, ``],
        [`Frimapic`, ``],
        [`Rivamar`, ``],
    ])],
    ["Unys", new Map([
        ["Amaillide",                ""],
        ["Arabelle",                 ""],
        ["Arpentières",              ""],
        ["Entrelasque",              ""],
        ["Forêt Blanche",            ""],
        ["Pont du Hameau",           ""],
        ["Rotombourg",               ""],
        ["Renouet",                  ""],
        ["Vaguelone",                ""],
        ["Ville Noire",              ""],
        ["Ogoesse",                  ""],
        ["Maillard",                 ""],
        ["Volucité",                 ""],
        ["Méanville",                ""],
        ["Port Yoneuve",             ""],
        ["Parsemille",               ""],
        ["Flocombe",                 ""],
        ["Janusia",                  ""],
        ["Pavonnay",                 ""],
        ["Ondes-sur-Mer",            ""],
        ["Papeloa",                  ""]
    ])],
    ["Kalos", new Map([
        ["Bourg Croquis",            ""],
        ["Quarellis",                ""],
        ["Fort-Vanitas",             ""],
        ["Roche-sur-Gliffe",         ""],
        ["Cromlac'h",                ""],
        ["La Frescale",              ""],
        ["Mozheim",                  ""],
        ["Batisques",                ""],
        ["Neuvartault",              ""],
        ["Relifac-le-Haut",          ""],
        ["Yantreizh",                ""],
        ["Port Tempères",            ""],
        ["Illumis",                  ""],
        ["Romant-sous-Bois",         ""],
        ["Flusselles",               ""],
        ["Auffrac-les-Congères",     ""]
    ])],
    ["Alola", new Map([
        ["Lili'i",                   ""],
        ["Ekaeka",                   ""],
        ["Ho'ohale",                 ""],
        ["Ohana",                    ""],
        ["Konikoni",                 ""],
        ["Malié",                    ""],
        ["Village Toko",             ""],
        ["Kokohio",                  ""],
        ["Village Flottant",         ""]
    ])],
    ["Galar", new Map([
        ["Paddoxton",                ""],
        ["Brasswick",                ""],
        ["Greenbury",                ""],
        ["Skifford",                 ""],
        ["Motorby",                  ""],
        ["Old Chister",              ""],
        ["Corrifey",                 ""],
        ["Ludester",                 ""],
        ["Smashings",                ""],
        ["Kickenham",                ""]
    ])],
    ["Paldea", new Map([
        ["Cuchalaga",                ""],
        ["Mesaledo",                 ""],
        ["Pinchoria",                ""],
        ["Plato Real",               ""],
        ["Porto Marinada",           ""],
        ["Alforneira",               ""],
        ["Cuencia",                  ""],
        ["Frigao",                   ""],
        ["Jarramanca",               ""],
        ["Levalendura",              ""],
        ["Mezclamora",               ""],
        ["Mont Nappé",               ""],
        ["Sevaro",                   ""]
    ])],
    ["Fiore", new Map([
        ["Printiville",              ""],
        ["Automnelle",               ""],
        ["Bourg-l'Hiver",            ""],
        ["Îlot-Eté",                 ""]
    ])],
    ["Almia", new Map([
        ["Bourg-Chicore",            ""],
        ["Véterville",               ""],
        ["Bonport",                  ""],
        ["Campement Froidur",        ""],
        ["Terruptive",               ""],
        ["Village Alorize",          ""]
    ])],
    ["Oblivia", new Map([
        ["Village Cocona",           ""],
        ["Pentoblique",              ""],
        ["Balnéaria",                ""]
    ])]
]);

const regionsToProfessors = new Map([
    ['Kanto', {nom: 'Chen', lieu: 'Bourg Palette'}],
    ['Johto', {nom: 'Orme', lieu: 'Bourg Geon'}],
    ['Hoenn', {nom: 'Seko', lieu: 'Bourg-en-Vol'}],
    ['Sinnoh', {nom: 'Sorbier', lieu: 'Littorella'}],
    ['Unys', {nom: 'Keteleeria', lieu: 'Renouet'}],
    ['Kalos', {nom: 'Platane', lieu: 'Illumis'}],
    ['Alola', {nom: 'Euphorbe', lieu: 'Mele-Mele'}],
    ['Galar', {nom: 'Sonya', lieu: 'Brasswick'}],
    ['Paldea', {nom: 'Olim/Turum', lieu: 'Zone Zéro'}],
]);

module.exports = { regionsAndCities, regionsToProfessors }